#-------------------------------
# General Site Settings

grandtitle: Demet Tuncer and the United Thracians
title: Demet Tuncer
description: and the United Thracians
email: unitedthracians@gmail.com

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: About Us, url: '#about-me'}
- {name: Musicians, url: '#clients'}
- {name: Work, url: '#work'}
- {name: Contact, url: '#contact'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Demet Tuncer and the United Thracians Music Band in Portland Oregon.'
  rel-author: 'https://www.youtube.com/c/DemetTuncer/'
  rel-publisher: 'http://aliergin.com'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------
# About Section

# NOTE: The avatar is defined in the all.sass document.

blurb: >
  **Our band** has a story to tell you. We are musician nomads currently calling Porland, Oregon home and would like to share what we have seen and heard all these years of moving. Some people call it the world music -- it is just the music to us. Rest assured, come join us to hear a tune you may never have heard of before and indulge yourself in a convenient tour around the world.

skills:
- {name: Communication, value: '9'}
- {name: Organization, value: '7'}
- {name: Learning, value: '10'}
- {name: Teaching, value: '6'}
- {name: Planning, value: '7'}
- {name: Visual Design, value: '5'}
- {name: UX Design, value: '8'}
- {name: Programming, value: '6'}

#-------------------------------
# Work Section

projects:
- {name: Pala Tute, folder: 'proj-1', file: 'assets/html/work/proj-1.html'}
- {name: Medley, folder: 'proj-7', file: 'assets/html/work/proj-7.html'}
- {name: Sway, folder: 'proj-2', file: 'assets/html/work/proj-2.html'}
- {name: Djelem, folder: 'proj-3', file: 'assets/html/work/proj-3.html'}
- {name: Goreceksin Kendini, folder: 'proj-4', file: 'assets/html/work/proj-4.html'}
- {name: Lela, folder: 'proj-5', file: 'assets/html/work/proj-5.html'}
# - {name: Bahcede, folder: 'proj-6', file: 'assets/html/work/proj-6.html'}




#-------------------------------
# Clients Section

clients:
- {avatar: 'mic.png',
  name: 'Demet Tuncer',
  title: 'Vocal cord operations',
  quote: '<p><strong>Demet</strong> is an actor, singer, digital content producer and performance artist known for combining acting and exceptional vocal talents. She studyied acting and musical theater, performed as lead singer in prestigious bands, such as Istanbul Gelisim, and held award-winning leading roles in well-known musical theater productions, such as Avenue Q, The Sound of Music, West Side Story, as well as performing in a wildly popular TV sitcom series Çocuklar Duymasın. Demet is working with United Thracians on her next musical storytelling project to celebrate diversity and culture through stories and songs from around the world. For more information on her work you can visit <a href="http://demettuncer.com" target="_blank">demettuncer.com</a></p>',
  logo: 'demet1.jpg'}
- {avatar: 'guitar.png',
  name: 'Mesut Ali Ergin',
  title: 'Sweeper for thin strings',
  quote: '<p><strong>Mesut Ali</strong> was born and raised in Istanbul, Turkey. After dissecting a number of vintage instruments at early age, he was found fit for an instrument-less discipline and sent in singing for the school choir at grade school. He continued singing bass partitions for multiple choirs, including ITU Polyphonic, IU Polyphonic Choir as well as the Turkish Music Choir of the State Conservatory, as they studied under the direction of Prof. Serdar Ozturk. In the following years, Mesut Ali played the guitar and sang for various groups in Turkey and USA, and has been a proud member of United Thracians. He is also an avid sound engineer-wannabe, with experience in live sound reinforcement, system tuning and mixing.</p>',
  logo: 'ali1.jpg'}
- {avatar: 'bass.png',
  name: 'Bugra Kaytanli',
  title: 'Dept of low frequency and thick strings',
  quote: '<p><strong>Bugra is .... </strong>Short bio follows.Short bio follows.Short bio follows.Short bio follows.Short bio follows.Short bio follows.Short bio follows.Short bio follows.Short bio follows.</p>',
  logo: 'bugra1.jpg'}
- {avatar: 'keys.png',
  name: 'Jan Porvas',
  title: 'Locksmith for black&white keys',
  quote: '<p><strong>Jan</strong> was born in Tabriz, Iran in 1984 and started his music studies at early age with the drums and the keyboard. He explored classical music of Azerbaijan and started to compose by the time he was 10-years-old. Jan has been a professional musician since he was 17-years old and played the daf, the keyboard, the piano and the tanbur in various bands. He has worked with master artist Cavit Murtezaoglu and explored the philosophy of music and continued his career in spiritual and mysticial music. Along with his work in musical compositions and arrangements, Jan has been teaching many students to play the daf at all levels. For more information on Jan and his work, please visit <a href="http://janporvas.com" target="_blank">janporvas.com</a></p>',
  logo: 'jan1.jpg'}
- {avatar: 'drums.png',
  name: 'Cagri Tanriover',
  title: 'Dept of resonators that can take a beating',
  quote: '<p><strong>Cagri</strong> was born in 1974 in Germany to a family where nobody played any instruments at all, except a few talented whistlers. His first encounters with musical instruments include playing the snare drums as part of the grade school’s marching band and the electronic keyboard his father got him. However, Cagri’s dominating interest in electronics turned the keyboard into a spare parts source for his ongoing hobby projects. More recently, he started playing the cajon and the darbuka for United Thracians and happy to make music with a group of talented and experienced musicians who have been kind enough to let him jam along.</p>',
  logo: 'cagri1.jpg'}

#-------------------------------
# Contact Section

social:
- {icon: 'twitter', link: 'http://twitter.com/devtipsshow'}
- {icon: 'dribbble', link: 'https://dribbble.com/travisneilson'}
- {icon: 'behance', link: 'https://www.behance.net/travisneilson'}
- {icon: 'youtube', link: 'https://www.youtube.com/DevTipsForDesigners'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/travisneilson/'}


# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
