#-------------------------------
# General Site Settings

grandtitle: Demet Tuncer and the United Thracians
title: Demet Tuncer
description: and the United Thracians
email: unitedthracians@gmail.com

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: About Us, url: '#about-me'}
- {name: Musicians, url: '#clients'}
- {name: Work, url: '#work'}
- {name: Contact, url: '#contact'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Demet Tuncer and the United Thracians Music Band in Portland Oregon.'
  rel-author: 'https://www.youtube.com/c/DemetTuncer/'
  rel-publisher: 'http://aliergin.com'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------
# About Section

# NOTE: The avatar is defined in the all.sass document.

blurb: >
  **Our band** has a story to tell you. We are musician nomads currently calling Porland, Oregon home and would like to share what we have seen and heard all these years of moving. Some people call it the world music -- it is just the music to us. Rest assured, come join us to hear a tune you may never have heard of before and indulge yourself in a convenient tour around the world.

skills:
- {name: Communication, value: '9'}
- {name: Organization, value: '7'}
- {name: Learning, value: '10'}
- {name: Teaching, value: '6'}
- {name: Planning, value: '7'}
- {name: Visual Design, value: '5'}
- {name: UX Design, value: '8'}
- {name: Programming, value: '6'}

#-------------------------------
# Work Section

projects:
- {name: Pala Tute, folder: 'proj-1', file: 'work/proj-1.html'}
- {name: Sway, folder: 'proj-2', file: 'work/proj-2.html'}
- {name: Djelem, folder: 'proj-3', file: 'work/proj-3.html'}
- {name: Goreceksin Kendini, folder: 'proj-4', file: 'work/proj-4.html'}
- {name: Lela, folder: 'proj-5', file: 'work/proj-5.html'}
- {name: Bahcede, folder: 'proj-6', file: 'work/proj-6.html'}




#-------------------------------
# Clients Section

clients:
- {avatar: 'mic.png',
  name: 'Demet Tuncer',
  title: 'Vocal cord operations',
  quote: '<p><strong>Demet</strong> is an actor, singer, digital content producer and performance artist known for combining acting and exceptional vocal talents. She studyied acting and musical theater, performed as lead singer in prestigious bands, such as Istanbul Gelisim, and held award-winning leading roles in well-known musical theater productions, such as Avenue Q, The Sound of Music, West Side Story, as well as performing in a wildly popular TV sitcom series Çocuklar Duymasın. Demet is working with United Thracians on her next musical storytelling project to celebrate diversity and culture through stories and songs from around the world. For more information on her work you can visit <a href="http://demettuncer.com" target="_blank">demettuncer.com</a></p>',
  logo: 'demet1.jpg'}
- {avatar: 'guitar.png',
  name: 'Mesut Ali Ergin',
  title: 'Sweeper for thin strings',
  quote: '<p><strong>Mesut Ali is .... </strong>Short bio follows.Short bio follows.Short bio follows.Short bio follows.Short bio follows.Short bio follows.Short bio follows.Short bio follows.Short bio follows.</p>',
  logo: 'ali1.jpg'}
- {avatar: 'bass.png',
  name: 'Bugra Kaytanli',
  title: 'Dept of low frequency and thick strings',
  quote: '<p><strong>Bugra is .... </strong>Short bio follows.Short bio follows.Short bio follows.Short bio follows.Short bio follows.Short bio follows.Short bio follows.Short bio follows.Short bio follows.</p>',
  logo: 'bugra1.jpg'}
- {avatar: 'keys.png',
  name: 'Jan Porvas',
  title: 'Locksmith for black&white keys',
  quote: '<p><strong>Jan is .... </strong>Short bio follows.Short bio follows.Short bio follows.Short bio follows.Short bio follows.Short bio follows.Short bio follows.Short bio follows.Short bio follows.</p>',
  logo: 'jan1.jpg'}
- {avatar: 'drums.png',
  name: 'Cagri Tanriover',
  title: 'Dept of resonators that can take a beating',
  quote: '<p><strong>Cagri is .... </strong>Short bio follows.Short bio follows.Short bio follows.Short bio follows.Short bio follows.Short bio follows.Short bio follows.Short bio follows.Short bio follows.</p>',
  logo: 'cagri1.jpg'}

#-------------------------------
# Contact Section

social:
- {icon: 'twitter', link: 'http://twitter.com/devtipsshow'}
- {icon: 'dribbble', link: 'https://dribbble.com/travisneilson'}
- {icon: 'behance', link: 'https://www.behance.net/travisneilson'}
- {icon: 'youtube', link: 'https://www.youtube.com/DevTipsForDesigners'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/travisneilson/'}


# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
