#-------------------------------
# General Site Settings

title: Demet Tuncer
description: and the United Thracians
email: unitedthracians@gmail.com

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: About Us, url: '#about-me'}
- {name: Musicians, url: '#clients'}
- {name: Work, url: '#work'}
- {name: Contact, url: '#contact'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Demet Tuncer and the United Thracians Music Band in Portland Oregon.'
  rel-author: 'https://www.youtube.com/c/DemetTuncer/'
  rel-publisher: 'http://aliergin.com'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------
# About Section

# NOTE: The avatar is defined in the all.sass document.

blurb: >
  **Travis specializes in making things** for human people.
  Most of the things he makes are [digital interfaces](http://travisneilson.com){:target="_blank"},
  but he also puts effort into crafting [next-level beats](http://soundcloud.com/travis-neilson){:target="_blank"}
  and [YouTube videos](http://youtube.com/user/devtipsfordesigners){:target="_blank"} about making codes happen.


skills:
- {name: Communication, value: '9'}
- {name: Organization, value: '7'}
- {name: Learning, value: '10'}
- {name: Teaching, value: '6'}
- {name: Planning, value: '7'}
- {name: Visual Design, value: '5'}
- {name: UX Design, value: '8'}
- {name: Programming, value: '6'}

#-------------------------------
# Work Section

projects:
- {name: TYPO International Design Talks, folder: 'proj-1', file: 'work/proj-1.html'}
- {name: City-IN website concept, folder: 'proj-2', file: 'work/proj-2.html'}
- {name: Crispy Icons, folder: 'proj-3', file: 'work/proj-3.html'}
- {name: Flat Mobile UI/UX Concept, folder: 'proj-4', file: 'work/proj-4.html'}
- {name: Fresh It Up, folder: 'proj-5', file: 'work/proj-5.html'}
- {name: Timeline Page, folder: 'proj-6', file: 'work/proj-6.html'}
- {name: Weather Dashboard, folder: 'proj-7', file: 'work/proj-7.html'}
- {name: Stripes & Co, folder: 'proj-8', file: 'work/proj-8.html'}




#-------------------------------
# Clients Section

clients:
- {avatar: 'mic.png',
  name: 'Demet Tuncer',
  title: 'Vocal cord operations',
  quote: '<p><strong>Demet is .... </strong>Short bio follows.Short bio follows.Short bio follows.Short bio follows.Short bio follows.Short bio follows.Short bio follows.Short bio follows.Short bio follows.</p>',
  logo: 'demet1.jpg'}
- {avatar: 'guitar.png',
  name: 'Mesut Ali Ergin',
  title: 'Sweeper for thin strings',
  quote: '<p><strong>Mesut Ali is .... </strong>Short bio follows.Short bio follows.Short bio follows.Short bio follows.Short bio follows.Short bio follows.Short bio follows.Short bio follows.Short bio follows.</p>',
  logo: 'ali1.jpg'}
- {avatar: 'bass.png',
  name: 'Bugra Kaytanli',
  title: 'Dept of low frequency and thick strings',
  quote: '<p><strong>Bugra is .... </strong>Short bio follows.Short bio follows.Short bio follows.Short bio follows.Short bio follows.Short bio follows.Short bio follows.Short bio follows.Short bio follows.</p>',
  logo: 'bugra1.jpg'}
- {avatar: 'keys.png',
  name: 'Jan Porvas',
  title: 'Locksmith for black&white keys',
  quote: '<p><strong>Jan is .... </strong>Short bio follows.Short bio follows.Short bio follows.Short bio follows.Short bio follows.Short bio follows.Short bio follows.Short bio follows.Short bio follows.</p>',
  logo: 'jan1.jpg'}
- {avatar: 'drums.png',
  name: 'Cagri Tanriover',
  title: 'Dept of resonators that can take a beating',
  quote: '<p><strong>Cagri is .... </strong>Short bio follows.Short bio follows.Short bio follows.Short bio follows.Short bio follows.Short bio follows.Short bio follows.Short bio follows.Short bio follows.</p>',
  logo: 'cagri1.jpg'}

#-------------------------------
# Contact Section

social:
- {icon: 'twitter', link: 'http://twitter.com/devtipsshow'}
- {icon: 'dribbble', link: 'https://dribbble.com/travisneilson'}
- {icon: 'behance', link: 'https://www.behance.net/travisneilson'}
- {icon: 'youtube', link: 'https://www.youtube.com/DevTipsForDesigners'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/travisneilson/'}


# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
